{{- range $ingress := .Values.services }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
  name: {{ $ingress.name }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $ingress.subDomain }}.dashboard.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $ingress.name }}
            port:
              number: 80
{{- end }}
